import { Injectable, signal } from '@angular/core';
import { Product } from '../models/product.model';
import { of, Observable } from 'rxjs';
import { delay } from 'rxjs/operators';

const PRODUCTS_DATA: Product[] = [
  {
    id: 1,
    name: 'Wireless Headphones',
    category: 'Electronics',
    price: 99.99,
    brand: 'SonicWave',
    description: 'Noise-cancelling over-ear headphones.',
    longDescription: 'Immerse yourself in pure sound with the SonicWave Pro headphones. Featuring advanced noise-cancellation technology, a 30-hour battery life, and crystal-clear audio, these headphones are perfect for music lovers and frequent travelers.',
    image: 'https://picsum.photos/id/1075/500/500',
    stock: 25,
    rating: 4.7,
    reviews: 1250,
  },
  {
    id: 2,
    name: 'Smartwatch Series 7',
    category: 'Electronics',
    price: 399.00,
    brand: 'TechVerse',
    description: 'Stay connected on the go.',
    longDescription: 'The TechVerse Smartwatch Series 7 is your ultimate fitness and health companion. Track your workouts, monitor your heart rate, and get notifications right on your wrist. With a stunning edge-to-edge display and a durable design, it’s built to keep up with your active lifestyle.',
    image: 'https://picsum.photos/id/2/500/500',
    stock: 15,
    rating: 4.9,
    reviews: 890,
  },
  {
    id: 3,
    name: 'Organic Green Tea',
    category: 'Groceries',
    price: 12.50,
    brand: 'PureLeaf',
    description: '100% organic antioxidant-rich green tea.',
    longDescription: 'Start your day with a cup of PureLeaf Organic Green Tea. Sourced from the finest tea gardens, our tea is packed with antioxidants and offers a smooth, refreshing taste. Each box contains 50 eco-friendly tea bags.',
    image: 'https://picsum.photos/id/41/500/500',
    stock: 100,
    rating: 4.5,
    reviews: 450,
  },
  {
    id: 4,
    name: 'Modern Leather Backpack',
    category: 'Fashion',
    price: 149.95,
    brand: 'UrbanCarry',
    description: 'Stylish and durable for daily use.',
    longDescription: 'The UrbanCarry backpack combines style and functionality. Made from genuine leather, it features a padded laptop compartment, multiple pockets for organization, and comfortable shoulder straps. Perfect for work, school, or travel.',
    image: 'https://picsum.photos/id/106/500/500',
    stock: 30,
    rating: 4.6,
    reviews: 320,
  },
  {
    id: 5,
    name: '4K Action Camera',
    category: 'Electronics',
    price: 249.99,
    brand: 'GoCapture',
    description: 'Capture your adventures in stunning 4K.',
    longDescription: 'The GoCapture Pro is a rugged, waterproof action camera that records breathtaking 4K video at 60fps. With advanced image stabilization and a wide-angle lens, you can capture smooth, immersive footage of all your adventures.',
    image: 'https://picsum.photos/id/250/500/500',
    stock: 18,
    rating: 4.8,
    reviews: 780,
  },
  {
    id: 6,
    name: 'Running Shoes',
    category: 'Footwear',
    price: 120.00,
    brand: 'FastFlex',
    description: 'Lightweight and responsive for runners.',
    longDescription: 'Experience ultimate comfort and performance with FastFlex running shoes. The lightweight mesh upper provides breathability, while the responsive foam midsole offers excellent cushioning and energy return. Ideal for both casual jogs and long-distance runs.',
    image: 'https://picsum.photos/id/21/500/500',
    stock: 50,
    rating: 4.7,
    reviews: 650,
  },
  {
    id: 7,
    name: 'Eco-Friendly Yoga Mat',
    category: 'Sports',
    price: 45.00,
    brand: 'ZenFlex',
    description: 'Non-slip, TPE material, perfect for yoga.',
    longDescription: 'Find your balance with the ZenFlex Eco-Friendly Yoga Mat. Made from biodegradable TPE material, this mat provides excellent grip and cushioning. It\'s lightweight, durable, and comes with a carrying strap for easy transport.',
    image: 'https://picsum.photos/id/146/500/500',
    stock: 60,
    rating: 4.8,
    reviews: 550,
  },
  {
    id: 8,
    name: 'Electric Kettle',
    category: 'Home Appliances',
    price: 55.50,
    brand: 'QuickBoil',
    description: '1.7L stainless steel fast-boil kettle.',
    longDescription: 'The QuickBoil Electric Kettle heats water faster than a microwave and safer than a stovetop. With a 1.7-liter capacity, automatic shut-off, and boil-dry protection, it\'s a convenient and safe addition to any kitchen.',
    image: 'https://picsum.photos/id/988/500/500',
    stock: 40,
    rating: 4.6,
    reviews: 410,
  },
  {
    id: 9,
    name: 'Novel - "The Last Server"',
    category: 'Books',
    price: 15.99,
    brand: 'PageTurner',
    description: 'A thrilling sci-fi adventure.',
    longDescription: 'Dive into a dystopian future where a single developer holds the key to humanity\'s last data repository. "The Last Server" is a gripping tale of code, conspiracy, and the fight for information freedom.',
    image: 'https://picsum.photos/id/24/500/500',
    stock: 120,
    rating: 4.9,
    reviews: 980,
  },
  {
    id: 10,
    name: 'Men\'s Classic Watch',
    category: 'Fashion',
    price: 299.99,
    brand: 'Timeless Co.',
    description: 'Elegant stainless steel design.',
    longDescription: 'A masterpiece of craftsmanship, the Timeless Co. classic watch features a sapphire crystal face, Swiss quartz movement, and a polished stainless steel band. Water-resistant up to 50 meters, it\'s the perfect accessory for any occasion.',
    image: 'https://picsum.photos/id/225/500/500',
    stock: 22,
    rating: 4.7,
    reviews: 430,
  },
  {
    id: 11,
    name: 'Portable Bluetooth Speaker',
    category: 'Electronics',
    price: 79.50,
    brand: 'SoundPod',
    description: 'Compact, waterproof, with rich bass.',
    longDescription: 'Take your music anywhere with the SoundPod portable speaker. This compact powerhouse is IPX7 waterproof, offers 12 hours of playtime, and delivers surprisingly deep bass for its size. Connect effortlessly via Bluetooth and get the party started.',
    image: 'https://picsum.photos/id/111/500/500',
    stock: 75,
    rating: 4.5,
    reviews: 1100,
  },
  {
    id: 12,
    name: 'Gourmet Coffee Beans',
    category: 'Groceries',
    price: 22.00,
    brand: 'AromaRoast',
    description: '1lb bag of single-origin Arabica beans.',
    longDescription: 'Awaken your senses with AromaRoast\'s single-origin Ethiopian Yirgacheffe coffee beans. This medium roast boasts bright, fruity, and floral notes. Sourced from fair-trade farms and roasted in small batches for maximum freshness.',
    image: 'https://picsum.photos/id/30/500/500',
    stock: 80,
    rating: 4.8,
    reviews: 760,
  },
  {
    id: 13,
    name: 'ProGamer Laptop X',
    category: 'Electronics',
    price: 1499.99,
    brand: 'PixelRig',
    description: 'High-performance gaming on the go.',
    longDescription: 'Unleash your gaming potential with the PixelRig ProGamer Laptop X. Featuring a latest-gen processor, a powerful graphics card, a 144Hz display, and a backlit RGB keyboard, it delivers an immersive and smooth gaming experience. It\'s the ultimate machine for serious gamers.',
    image: 'https://picsum.photos/id/160/500/500',
    stock: 10,
    rating: 4.8,
    reviews: 210,
  },
  {
    id: 14,
    name: 'SkySailor Drone',
    category: 'Electronics',
    price: 499.00,
    brand: 'AeroView',
    description: '4K camera drone for stunning aerial shots.',
    longDescription: 'Explore the world from a new perspective with the AeroView SkySailor Drone. It captures stunning 4K video and 12MP photos. With intelligent flight modes, a 30-minute flight time, and a 5km range, it\'s easy for anyone to fly and capture professional-quality aerial footage.',
    image: 'https://picsum.photos/id/431/500/500',
    stock: 20,
    rating: 4.7,
    reviews: 340,
  },
  {
    id: 15,
    name: 'Fusion Blender 5000',
    category: 'Home Appliances',
    price: 129.95,
    brand: 'KitchenPro',
    description: 'Powerful blender for smoothies and more.',
    longDescription: 'The KitchenPro Fusion Blender 5000 makes it easy to create delicious smoothies, soups, and sauces. Its powerful 1200-watt motor and stainless steel blades can handle even the toughest ingredients. Comes with a large 64oz pitcher and a tamper.',
    image: 'https://picsum.photos/id/985/500/500',
    stock: 35,
    rating: 4.6,
    reviews: 600,
  },
  {
    id: 16,
    name: '8-Piece Knife Block Set',
    category: 'Home Appliances',
    price: 89.99,
    brand: 'SharpEdge',
    description: 'High-carbon stainless steel knife set.',
    longDescription: 'Upgrade your kitchen with the SharpEdge 8-Piece Knife Block Set. Forged from high-carbon stainless steel, these knives offer precision and durability. The set includes a chef\'s knife, bread knife, Santoku knife, utility knife, paring knife, and shears, all housed in a stylish wooden block.',
    image: 'https://picsum.photos/id/223/500/500',
    stock: 45,
    rating: 4.7,
    reviews: 310,
  },
  {
    id: 17,
    name: 'Novel - "Shadows of Eldoria"',
    category: 'Books',
    price: 18.50,
    brand: 'PageTurner',
    description: 'An epic fantasy of magic and betrayal.',
    longDescription: 'In the land of Eldoria, an ancient evil stirs. "Shadows of Eldoria" follows a young mage on a perilous quest to uncover a conspiracy that threatens to plunge the kingdom into eternal darkness. A must-read for fantasy lovers.',
    image: 'https://picsum.photos/id/379/500/500',
    stock: 150,
    rating: 4.8,
    reviews: 1150,
  },
  {
    id: 18,
    name: 'Men\'s Classic Denim Jacket',
    category: 'Fashion',
    price: 85.00,
    brand: 'UrbanCarry',
    description: 'Timeless style, rugged and comfortable.',
    longDescription: 'A wardrobe staple, the UrbanCarry Classic Denim Jacket is made from premium, durable denim. With a comfortable fit, button-front closure, and classic pocket styling, it\'s a versatile piece that never goes out of style.',
    image: 'https://picsum.photos/id/1011/500/500',
    stock: 40,
    rating: 4.5,
    reviews: 280,
  },
  {
    id: 19,
    name: 'Adjustable Dumbbell Set (50 lbs)',
    category: 'Sports',
    price: 199.99,
    brand: 'FitForce',
    description: 'Space-saving adjustable dumbbells.',
    longDescription: 'Get a full-body workout at home with the FitForce Adjustable Dumbbell Set. Easily adjust the weight from 5 to 50 lbs with a simple dial system. This space-saving design replaces 15 sets of weights, making it perfect for any home gym.',
    image: 'https://picsum.photos/id/823/500/500',
    stock: 25,
    rating: 4.9,
    reviews: 480,
  },
  {
    id: 20,
    name: '70% Cacao Dark Chocolate Bar',
    category: 'Groceries',
    price: 5.99,
    brand: 'ChocoPure',
    description: 'Rich and intense single-origin chocolate.',
    longDescription: 'Indulge in the deep, complex flavors of ChocoPure\'s 70% Cacao Dark Chocolate. Made from single-origin beans from Peru, this bar has notes of fruit and nuts. It\'s organic, fair-trade, and irresistibly delicious.',
    image: 'https://picsum.photos/id/435/500/500',
    stock: 200,
    rating: 4.9,
    reviews: 950,
  },
  // New Products Start Here
  // Books
  {
    id: 21,
    name: 'The Art of Programming',
    category: 'Books',
    price: 49.99,
    brand: 'CodePress',
    description: 'A deep dive into modern software design.',
    longDescription: 'This comprehensive guide covers fundamental principles of software architecture, design patterns, and best practices for writing clean, efficient, and maintainable code.',
    image: 'https://picsum.photos/id/28/500/500',
    stock: 80,
    rating: 4.9,
    reviews: 1500,
  },
  {
    id: 22,
    name: 'A History of Ancient Worlds',
    category: 'Books',
    price: 29.99,
    brand: 'Past Times Publishing',
    description: 'Explore the rise and fall of great civilizations.',
    longDescription: 'From the Mesopotamians to the Romans, this book offers a captivating journey through the ancient world, exploring their cultures, innovations, and conflicts.',
    image: 'https://picsum.photos/id/180/500/500',
    stock: 110,
    rating: 4.7,
    reviews: 820,
  },
  {
    id: 23,
    name: 'The Midnight Gardener',
    category: 'Books',
    price: 14.99,
    brand: 'PageTurner',
    description: 'A gripping mystery novel.',
    longDescription: 'A detective story set in a Victorian-era London, where a series of mysterious events in a botanical garden uncovers a dark secret.',
    image: 'https://picsum.photos/id/305/500/500',
    stock: 200,
    rating: 4.6,
    reviews: 750,
  },
  {
    id: 24,
    name: 'Galactic Empires',
    category: 'Books',
    price: 22.50,
    brand: 'SciFi World',
    description: 'An epic space opera saga.',
    longDescription: 'Spanning galaxies and generations, this sci-fi epic tells the story of warring factions in a distant future, fighting for control of the cosmos.',
    image: 'https://picsum.photos/id/312/500/500',
    stock: 90,
    rating: 4.8,
    reviews: 1200,
  },
  {
    id: 25,
    name: 'The Chef\'s Companion',
    category: 'Books',
    price: 35.00,
    brand: 'Kitchen Press',
    description: 'A comprehensive guide to culinary techniques.',
    longDescription: 'From basic knife skills to advanced pastry making, this cookbook is an essential resource for both aspiring and experienced chefs.',
    image: 'https://picsum.photos/id/326/500/500',
    stock: 150,
    rating: 4.9,
    reviews: 1100,
  },
  // Electronics
  {
    id: 26,
    name: 'Pro Gaming Mouse',
    category: 'Electronics',
    price: 69.99,
    brand: 'PixelRig',
    description: 'Ultra-lightweight mouse with 16,000 DPI sensor.',
    longDescription: 'Gain a competitive edge with the Pro Gaming Mouse. Its ergonomic design, customizable RGB lighting, and precision sensor make it the perfect tool for esports athletes.',
    image: 'https://picsum.photos/id/175/500/500',
    stock: 60,
    rating: 4.8,
    reviews: 950,
  },
  {
    id: 27,
    name: 'Mechanical Keyboard',
    category: 'Electronics',
    price: 129.99,
    brand: 'PixelRig',
    description: 'RGB backlit with customizable keys.',
    longDescription: 'Experience superior typing and gaming with our mechanical keyboard. Featuring responsive switches, full RGB backlighting, and a durable aluminum frame.',
    image: 'https://picsum.photos/id/48/500/500',
    stock: 45,
    rating: 4.9,
    reviews: 1300,
  },
  {
    id: 28,
    name: '27-inch 4K Monitor',
    category: 'Electronics',
    price: 449.00,
    brand: 'TechVerse',
    description: 'Vibrant colors and crisp details.',
    longDescription: 'Upgrade your workspace or gaming setup with this stunning 27-inch 4K monitor. With HDR support and a bezel-less design, it provides an immersive viewing experience.',
    image: 'https://picsum.photos/id/12/500/500',
    stock: 30,
    rating: 4.8,
    reviews: 850,
  },
  {
    id: 29,
    name: 'VR Headset',
    category: 'Electronics',
    price: 349.00,
    brand: 'TechVerse',
    description: 'Step into new worlds with virtual reality.',
    longDescription: 'The next generation of VR is here. Explore immersive games, apps, and experiences with this comfortable and powerful all-in-one VR headset.',
    image: 'https://picsum.photos/id/110/500/500',
    stock: 20,
    rating: 4.7,
    reviews: 650,
  },
  {
    id: 30,
    name: 'Wireless Earbuds',
    category: 'Electronics',
    price: 129.00,
    brand: 'SonicWave',
    description: 'True wireless with charging case.',
    longDescription: 'Enjoy the freedom of true wireless audio. These earbuds offer high-fidelity sound, a comfortable fit, and up to 24 hours of listening time with the included charging case.',
    image: 'https://picsum.photos/id/112/500/500',
    stock: 100,
    rating: 4.6,
    reviews: 2500,
  },
  {
    id: 31,
    name: 'Smart Speaker',
    category: 'Electronics',
    price: 89.99,
    brand: 'TechVerse',
    description: 'Your voice-controlled smart assistant.',
    longDescription: 'Play music, set alarms, get news, and control your smart home with just your voice. This smart speaker delivers rich sound in a compact design.',
    image: 'https://picsum.photos/id/103/500/500',
    stock: 80,
    rating: 4.7,
    reviews: 1800,
  },
  // Home Appliances
  {
    id: 32,
    name: 'Robot Vacuum Cleaner',
    category: 'Home Appliances',
    price: 299.99,
    brand: 'KitchenPro',
    description: 'Automated cleaning for your home.',
    longDescription: 'Keep your floors spotless with this intelligent robot vacuum. It maps your home, avoids obstacles, and automatically returns to its dock to recharge.',
    image: 'https://picsum.photos/id/355/500/500',
    stock: 25,
    rating: 4.8,
    reviews: 1200,
  },
  {
    id: 33,
    name: 'Air Fryer',
    category: 'Home Appliances',
    price: 89.99,
    brand: 'KitchenPro',
    description: 'Enjoy crispy food with less oil.',
    longDescription: 'The KitchenPro Air Fryer lets you cook your favorite fried foods with up to 75% less fat. Its large capacity is perfect for family meals.',
    image: 'https://picsum.photos/id/404/500/500',
    stock: 60,
    rating: 4.9,
    reviews: 3200,
  },
  {
    id: 34,
    name: 'Stand Mixer',
    category: 'Home Appliances',
    price: 249.99,
    brand: 'KitchenPro',
    description: 'The ultimate tool for bakers.',
    longDescription: 'From kneading dough to whipping cream, this powerful stand mixer handles it all. It comes with multiple attachments to tackle any recipe.',
    image: 'https://picsum.photos/id/450/500/500',
    stock: 30,
    rating: 4.9,
    reviews: 1800,
  },
  {
    id: 35,
    name: 'Coffee Maker',
    category: 'Home Appliances',
    price: 79.99,
    brand: 'QuickBoil',
    description: 'Brew delicious coffee every morning.',
    longDescription: 'Wake up to the smell of fresh coffee with this programmable 12-cup coffee maker. It features a brew-pause function and a permanent filter.',
    image: 'https://picsum.photos/id/342/500/500',
    stock: 70,
    rating: 4.6,
    reviews: 1500,
  },
  {
    id: 36,
    name: 'Air Purifier',
    category: 'Home Appliances',
    price: 149.99,
    brand: 'PureHome',
    description: 'Breathe cleaner, fresher air.',
    longDescription: 'This air purifier captures 99.97% of airborne particles, including dust, pollen, and smoke. Its quiet operation makes it perfect for bedrooms and offices.',
    image: 'https://picsum.photos/id/553/500/500',
    stock: 40,
    rating: 4.8,
    reviews: 900,
  },
  // Fashion
  {
    id: 37,
    name: 'Cashmere Sweater',
    category: 'Fashion',
    price: 189.00,
    brand: 'Timeless Co.',
    description: 'Luxuriously soft and warm.',
    longDescription: 'Made from 100% pure cashmere, this sweater is incredibly soft and provides exceptional warmth without the bulk. A timeless addition to any wardrobe.',
    image: 'https://picsum.photos/id/646/500/500',
    stock: 50,
    rating: 4.9,
    reviews: 350,
  },
  {
    id: 38,
    name: 'Classic Sunglasses',
    category: 'Fashion',
    price: 120.00,
    brand: 'UrbanCarry',
    description: 'Timeless style with UV protection.',
    longDescription: 'Protect your eyes in style with these classic sunglasses. They feature polarized lenses for glare reduction and 100% UV protection.',
    image: 'https://picsum.photos/id/659/500/500',
    stock: 80,
    rating: 4.7,
    reviews: 600,
  },
  {
    id: 39,
    name: 'Leather Belt',
    category: 'Fashion',
    price: 49.95,
    brand: 'UrbanCarry',
    description: 'Genuine leather with a classic buckle.',
    longDescription: 'This versatile belt is crafted from high-quality genuine leather and features a polished metal buckle. It\'s the perfect finishing touch for any outfit.',
    image: 'https://picsum.photos/id/474/500/500',
    stock: 120,
    rating: 4.6,
    reviews: 780,
  },
  {
    id: 40,
    name: 'Silk Scarf',
    category: 'Fashion',
    price: 65.00,
    brand: 'Timeless Co.',
    description: 'Elegant and versatile accessory.',
    longDescription: 'Made from 100% pure silk, this beautiful scarf features a vibrant print and can be styled in numerous ways. A perfect accessory for any season.',
    image: 'https://picsum.photos/id/1012/500/500',
    stock: 90,
    rating: 4.8,
    reviews: 250,
  },
  // Sports
  {
    id: 41,
    name: 'Basketball',
    category: 'Sports',
    price: 29.99,
    brand: 'FitForce',
    description: 'Official size and weight for indoor/outdoor use.',
    longDescription: 'This basketball offers superior grip and control, making it perfect for both competitive games and casual play on any surface.',
    image: 'https://picsum.photos/id/1070/500/500',
    stock: 150,
    rating: 4.7,
    reviews: 880,
  },
  {
    id: 42,
    name: 'Tennis Racket',
    category: 'Sports',
    price: 89.00,
    brand: 'ZenFlex',
    description: 'Lightweight frame for power and control.',
    longDescription: 'Ideal for intermediate players, this tennis racket provides a great balance of power and control. Its lightweight design allows for faster swings.',
    image: 'https://picsum.photos/id/1083/500/500',
    stock: 70,
    rating: 4.6,
    reviews: 420,
  },
  {
    id: 43,
    name: 'Resistance Bands Set',
    category: 'Sports',
    price: 24.99,
    brand: 'FitForce',
    description: 'Versatile bands for a full-body workout.',
    longDescription: 'This set of five resistance bands offers different levels of resistance, making it perfect for strength training, physical therapy, and stretching.',
    image: 'https://picsum.photos/id/1066/500/500',
    stock: 200,
    rating: 4.8,
    reviews: 1500,
  },
  {
    id: 44,
    name: 'Gym Bag',
    category: 'Sports',
    price: 39.95,
    brand: 'UrbanCarry',
    description: 'Durable and spacious for all your gear.',
    longDescription: 'This gym bag has a large main compartment, a ventilated shoe pocket, and multiple pockets to keep your gear organized and accessible.',
    image: 'https://picsum.photos/id/984/500/500',
    stock: 110,
    rating: 4.7,
    reviews: 950,
  },
  // Groceries
  {
    id: 45,
    name: 'Artisanal Sourdough Bread',
    category: 'Groceries',
    price: 7.99,
    brand: 'PureLoaf Bakery',
    description: 'Naturally leavened with a crispy crust.',
    longDescription: 'Baked fresh daily, our sourdough bread is made using traditional methods for a tangy flavor and a satisfyingly chewy texture.',
    image: 'https://picsum.photos/id/349/500/500',
    stock: 50,
    rating: 4.9,
    reviews: 450,
  },
  {
    id: 46,
    name: 'Greek Yogurt',
    category: 'Groceries',
    price: 5.49,
    brand: 'PureLeaf',
    description: 'Thick, creamy, and high in protein.',
    longDescription: 'Our plain Greek yogurt is a versatile and healthy choice for breakfast, snacks, or as a substitute for sour cream in recipes.',
    image: 'https://picsum.photos/id/292/500/500',
    stock: 120,
    rating: 4.8,
    reviews: 680,
  },
  {
    id: 47,
    name: 'Organic Honey',
    category: 'Groceries',
    price: 9.99,
    brand: 'PureLeaf',
    description: 'Raw and unfiltered for maximum flavor.',
    longDescription: 'Sourced from wildflowers, our organic honey is pure, raw, and unfiltered, retaining all its natural nutrients and beneficial enzymes.',
    image: 'https://picsum.photos/id/137/500/500',
    stock: 90,
    rating: 4.9,
    reviews: 720,
  },
  {
    id: 48,
    name: 'Sparkling Water Pack',
    category: 'Groceries',
    price: 15.99,
    brand: 'AquaFizz',
    description: 'A case of 24 cans of natural sparkling water.',
    longDescription: 'Enjoy the crisp, refreshing taste of our natural sparkling mineral water. Zero calories, zero sweeteners, just pure hydration.',
    image: 'https://picsum.photos/id/139/500/500',
    stock: 80,
    rating: 4.7,
    reviews: 550,
  },
  // Footwear
  {
    id: 49,
    name: 'Hiking Boots',
    category: 'Footwear',
    price: 159.99,
    brand: 'FastFlex',
    description: 'Waterproof and durable for any trail.',
    longDescription: 'Conquer any terrain with these rugged hiking boots. They feature a waterproof membrane, excellent ankle support, and a high-traction outsole.',
    image: 'https://picsum.photos/id/1021/500/500',
    stock: 40,
    rating: 4.8,
    reviews: 780,
  },
  {
    id: 50,
    name: 'Leather Dress Shoes',
    category: 'Footwear',
    price: 199.00,
    brand: 'Timeless Co.',
    description: 'Classic style for formal occasions.',
    longDescription: 'Handcrafted from premium leather, these elegant dress shoes are the perfect choice for business meetings, weddings, and other formal events.',
    image: 'https://picsum.photos/id/1059/500/500',
    stock: 60,
    rating: 4.9,
    reviews: 400,
  },
  {
    id: 51,
    name: 'Canvas Sneakers',
    category: 'Footwear',
    price: 59.95,
    brand: 'UrbanCarry',
    description: 'Comfortable and casual for everyday wear.',
    longDescription: 'These versatile canvas sneakers are a wardrobe staple. They feature a cushioned insole for all-day comfort and a durable rubber sole.',
    image: 'https://picsum.photos/id/1072/500/500',
    stock: 150,
    rating: 4.6,
    reviews: 1200,
  },
  {
    id: 52,
    name: 'Summer Sandals',
    category: 'Footwear',
    price: 45.00,
    brand: 'ZenFlex',
    description: 'Lightweight and stylish for warm weather.',
    longDescription: 'Stay cool and comfortable in these stylish summer sandals. They feature a soft footbed and adjustable straps for a perfect fit.',
    image: 'https://picsum.photos/id/1076/500/500',
    stock: 100,
    rating: 4.5,
    reviews: 650,
  }
];

@Injectable({ providedIn: 'root' })
export class ProductService {
  private products = signal<Product[]>(PRODUCTS_DATA);

  getProducts(): Observable<Product[]> {
    return of(this.products()).pipe(delay(200));
  }

  getProductById(id: number): Observable<Product | undefined> {
    const product = this.products().find(p => p.id === id);
    return of(product).pipe(delay(100));
  }

  addProduct(productData: Omit<Product, 'id' | 'rating' | 'reviews'>): Observable<Product> {
    const newId = Math.max(...this.products().map(p => p.id)) + 1;
    const newProduct: Product = {
      ...productData,
      id: newId,
      rating: 0,
      reviews: 0,
    };
    this.products.update(products => [...products, newProduct]);
    return of(newProduct).pipe(delay(100));
  }

  updateProduct(updatedProduct: Product): Observable<Product> {
    this.products.update(products => 
      products.map(p => p.id === updatedProduct.id ? updatedProduct : p)
    );
    return of(updatedProduct).pipe(delay(100));
  }

  deleteProduct(productId: number): Observable<{ success: boolean }> {
    this.products.update(products => products.filter(p => p.id !== productId));
    return of({ success: true }).pipe(delay(100));
  }
}
