import { Injectable } from '@angular/core';
import { Product } from '../models/product.model';
import { of, Observable } from 'rxjs';
import { delay } from 'rxjs/operators';

const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Wireless Headphones',
    category: 'Electronics',
    price: 99.99,
    brand: 'SonicWave',
    description: 'Noise-cancelling over-ear headphones.',
    longDescription: 'Immerse yourself in pure sound with the SonicWave Pro headphones. Featuring advanced noise-cancellation technology, a 30-hour battery life, and crystal-clear audio, these headphones are perfect for music lovers and frequent travelers.',
    image: 'https://picsum.photos/id/1075/500/500',
    stock: 25,
    rating: 4.7,
    reviews: 1250,
  },
  {
    id: 2,
    name: 'Smartwatch Series 7',
    category: 'Electronics',
    price: 399.00,
    brand: 'TechVerse',
    description: 'Stay connected on the go.',
    longDescription: 'The TechVerse Smartwatch Series 7 is your ultimate fitness and health companion. Track your workouts, monitor your heart rate, and get notifications right on your wrist. With a stunning edge-to-edge display and a durable design, it’s built to keep up with your active lifestyle.',
    image: 'https://picsum.photos/id/2/500/500',
    stock: 15,
    rating: 4.9,
    reviews: 890,
  },
  {
    id: 3,
    name: 'Organic Green Tea',
    category: 'Groceries',
    price: 12.50,
    brand: 'PureLeaf',
    description: '100% organic antioxidant-rich green tea.',
    longDescription: 'Start your day with a cup of PureLeaf Organic Green Tea. Sourced from the finest tea gardens, our tea is packed with antioxidants and offers a smooth, refreshing taste. Each box contains 50 eco-friendly tea bags.',
    image: 'https://picsum.photos/id/41/500/500',
    stock: 100,
    rating: 4.5,
    reviews: 450,
  },
  {
    id: 4,
    name: 'Modern Leather Backpack',
    category: 'Fashion',
    price: 149.95,
    brand: 'UrbanCarry',
    description: 'Stylish and durable for daily use.',
    longDescription: 'The UrbanCarry backpack combines style and functionality. Made from genuine leather, it features a padded laptop compartment, multiple pockets for organization, and comfortable shoulder straps. Perfect for work, school, or travel.',
    image: 'https://picsum.photos/id/106/500/500',
    stock: 30,
    rating: 4.6,
    reviews: 320,
  },
  {
    id: 5,
    name: '4K Action Camera',
    category: 'Electronics',
    price: 249.99,
    brand: 'GoCapture',
    description: 'Capture your adventures in stunning 4K.',
    longDescription: 'The GoCapture Pro is a rugged, waterproof action camera that records breathtaking 4K video at 60fps. With advanced image stabilization and a wide-angle lens, you can capture smooth, immersive footage of all your adventures.',
    image: 'https://picsum.photos/id/250/500/500',
    stock: 18,
    rating: 4.8,
    reviews: 780,
  },
  {
    id: 6,
    name: 'Running Shoes',
    category: 'Footwear',
    price: 120.00,
    brand: 'FastFlex',
    description: 'Lightweight and responsive for runners.',
    longDescription: 'Experience ultimate comfort and performance with FastFlex running shoes. The lightweight mesh upper provides breathability, while the responsive foam midsole offers excellent cushioning and energy return. Ideal for both casual jogs and long-distance runs.',
    image: 'https://picsum.photos/id/21/500/500',
    stock: 50,
    rating: 4.7,
    reviews: 650,
  },
  {
    id: 7,
    name: 'Eco-Friendly Yoga Mat',
    category: 'Sports',
    price: 45.00,
    brand: 'ZenFlex',
    description: 'Non-slip, TPE material, perfect for yoga.',
    longDescription: 'Find your balance with the ZenFlex Eco-Friendly Yoga Mat. Made from biodegradable TPE material, this mat provides excellent grip and cushioning. It\'s lightweight, durable, and comes with a carrying strap for easy transport.',
    image: 'https://picsum.photos/id/146/500/500',
    stock: 60,
    rating: 4.8,
    reviews: 550,
  },
  {
    id: 8,
    name: 'Electric Kettle',
    category: 'Home Appliances',
    price: 55.50,
    brand: 'QuickBoil',
    description: '1.7L stainless steel fast-boil kettle.',
    longDescription: 'The QuickBoil Electric Kettle heats water faster than a microwave and safer than a stovetop. With a 1.7-liter capacity, automatic shut-off, and boil-dry protection, it\'s a convenient and safe addition to any kitchen.',
    image: 'https://picsum.photos/id/988/500/500',
    stock: 40,
    rating: 4.6,
    reviews: 410,
  },
  {
    id: 9,
    name: 'Novel - "The Last Server"',
    category: 'Books',
    price: 15.99,
    brand: 'PageTurner',
    description: 'A thrilling sci-fi adventure.',
    longDescription: 'Dive into a dystopian future where a single developer holds the key to humanity\'s last data repository. "The Last Server" is a gripping tale of code, conspiracy, and the fight for information freedom.',
    image: 'https://picsum.photos/id/24/500/500',
    stock: 120,
    rating: 4.9,
    reviews: 980,
  },
  {
    id: 10,
    name: 'Men\'s Classic Watch',
    category: 'Fashion',
    price: 299.99,
    brand: 'Timeless Co.',
    description: 'Elegant stainless steel design.',
    longDescription: 'A masterpiece of craftsmanship, the Timeless Co. classic watch features a sapphire crystal face, Swiss quartz movement, and a polished stainless steel band. Water-resistant up to 50 meters, it\'s the perfect accessory for any occasion.',
    image: 'https://picsum.photos/id/225/500/500',
    stock: 22,
    rating: 4.7,
    reviews: 430,
  },
  {
    id: 11,
    name: 'Portable Bluetooth Speaker',
    category: 'Electronics',
    price: 79.50,
    brand: 'SoundPod',
    description: 'Compact, waterproof, with rich bass.',
    longDescription: 'Take your music anywhere with the SoundPod portable speaker. This compact powerhouse is IPX7 waterproof, offers 12 hours of playtime, and delivers surprisingly deep bass for its size. Connect effortlessly via Bluetooth and get the party started.',
    image: 'https://picsum.photos/id/111/500/500',
    stock: 75,
    rating: 4.5,
    reviews: 1100,
  },
  {
    id: 12,
    name: 'Gourmet Coffee Beans',
    category: 'Groceries',
    price: 22.00,
    brand: 'AromaRoast',
    description: '1lb bag of single-origin Arabica beans.',
    longDescription: 'Awaken your senses with AromaRoast\'s single-origin Ethiopian Yirgacheffe coffee beans. This medium roast boasts bright, fruity, and floral notes. Sourced from fair-trade farms and roasted in small batches for maximum freshness.',
    image: 'https://picsum.photos/id/30/500/500',
    stock: 80,
    rating: 4.8,
    reviews: 760,
  }
];

@Injectable({ providedIn: 'root' })
export class ProductService {
  getProducts(): Observable<Product[]> {
    return of(PRODUCTS).pipe(delay(200));
  }

  getProductById(id: number): Observable<Product | undefined> {
    const product = PRODUCTS.find(p => p.id === id);
    return of(product).pipe(delay(100));
  }
}